version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build-and-test:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: First Step
          command: |
            echo "Hello World"
            echo "This is the delivery pipeline"
      - run:
          name: Second Step
          command: |
            ls -la
            echo "The files in my repo"

workflows:
  sample:
    jobs:
      - build-and-test